In [ ]:
%matplotlib inline


什么是PyTorch?
================

这是一个基于Python的科学计算包，其旨在服务两类场合

- 替代numpy发挥GPU潜能
- 一个提供了高度灵活性和效率的深度学习实验性平台


开始
---------------

Tensors


Tensors和numpy中的ndarrays较为相似, 与此同时Tensor也能够使用GPU来加速运算。



In [1]:
from __future__ import print_function
import torch

构建一个未初始化的5*3矩阵

In [4]:
x = torch.empty(5, 3)
print(x)

tensor([[ 0.0000e+00,  0.0000e+00,  1.3733e-42],
        [ 0.0000e+00,  7.0065e-45,  0.0000e+00],
        [ 7.6238e+08,  5.4230e-43,  0.0000e+00],
        [ 0.0000e+00,  9.1843e-41,  0.0000e+00],
        [ 8.8743e+08,  5.4230e-43,  0.0000e+00]])


构建一个随机初始化的矩阵



In [5]:
x = torch.rand(5, 3)
print(x)

tensor([[ 0.3033,  0.0005,  0.7131],
        [ 0.8024,  0.8223,  0.2878],
        [ 0.4480,  0.9465,  0.3888],
        [ 0.0029,  0.6421,  0.7353],
        [ 0.2377,  0.2970,  0.5093]])


构建一个0矩阵，数据类型为long



In [6]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])


直接从数据中构建tensor



In [7]:
x = torch.tensor([5.5, 3])
print(x)

tensor([ 5.5000,  3.0000])


或者是基于已经存在的tensor创建tensor。这些方法会复用输入张量的属性，比如dtype，除非用户提供了新的值。


In [8]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* 的方法输入是size
print(x)

x = torch.randn_like(x, dtype=torch.float)    # 重写dtype
print(x)                                      # 结果有相同的size

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)
tensor([[ 0.0530, -0.8755, -0.8630],
        [ 0.0889,  0.7886,  0.1081],
        [-1.2099, -0.1259,  0.4774],
        [ 0.1187,  0.0942,  0.7791],
        [-1.7884, -1.2375,  1.8421]])


获取它的size



In [9]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>注意</h4><p>``torch.Size`` 实际上是一个tuple，所以它支持所有的tuple操作</p></div>


Operations
---------------
操作有多种语法。在下面的示例中，我们将查看加法操作。


加法：语法1



In [10]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.2156, -0.7562, -0.0616],
        [ 0.8738,  1.7374,  0.5208],
        [-0.4377,  0.4482,  0.5068],
        [ 0.8632,  0.8912,  1.5788],
        [-1.3056, -0.4241,  2.2794]])


加法：语法2



In [11]:
print(torch.add(x, y))

tensor([[ 0.2156, -0.7562, -0.0616],
        [ 0.8738,  1.7374,  0.5208],
        [-0.4377,  0.4482,  0.5068],
        [ 0.8632,  0.8912,  1.5788],
        [-1.3056, -0.4241,  2.2794]])


加法：提供一个额外的参数作为输出



In [ ]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

加法: 原地操作



In [ ]:
# adds x to y
y.add_(x)
print(y)

<div class="alert alert-info"><h4>注意</h4><p>任何使张量就地改变的变形的操作都是用 ``_``结尾的.
    例如: ``x.copy_(y)``, ``x.t_()`` 会改变 ``x``.</p></div>

你可以使用标准的NumPy索引来访问张量。



In [ ]:
print(x[:, 1])

变形： 如果你想要 resize/reshape 张量, 你可以使用 ``torch.view``:



In [ ]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # 尺寸 -1 是从其他维度推断出来的
print(x.size(), y.size(), z.size())

如果你有一个单元素张量，使用 ``.item()`` 来获得其作为python的数字类型



In [ ]:
x = torch.randn(1)
print(x)
print(x.item())

**进一步阅读:**


  100+ Tensor的操作，包括换位、索引、切片、数学运算、线性算法和随机数等等
  
  详见[http://pytorch.org/docs/torch](http://pytorch.org/docs/torch).

NumPy Bridge
------------

Torch Tensor和 NumPy array 的转换是非常容易的。

注意Torch的Tensor和numpy数组是共享存储空间的，修改一个会导致另外的一个也被修改。

将tensor转换为numpy数组
------------



In [14]:
a = torch.ones(5)
print(a)

tensor([ 1.,  1.,  1.,  1.,  1.])


In [15]:
b = a.numpy()
print(b)

[ 1.  1.  1.  1.  1.]


See how the numpy array changed in value.



In [16]:
a.add_(1)
print(a)
print(b)

tensor([ 2.,  2.,  2.,  2.,  2.])
[ 2.  2.  2.  2.  2.]


将numpy 数组转换为tensor
------------------------
注意更改numpy数组如何自动更改Tensor



In [17]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]
tensor([ 2.,  2.,  2.,  2.,  2.], dtype=torch.float64)


除了CharTensor，CPU上所有的Tensor都支持转换为numpy数组返回

CUDA 张量
------------

Tensors 可以使用 ``.to`` 方法移动到任意设备上.



In [18]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # 一个 CUDA 设备对象
    y = torch.ones_like(x, device=device)  # 直接构建一个在GPU上的Tensor
    x = x.to(device)                       # 或者直接使用字符串 ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` 也可以一起改变dtype

tensor([[ 1.0530,  0.1245,  0.1370],
        [ 1.0889,  1.7886,  1.1081],
        [-0.2099,  0.8741,  1.4774],
        [ 1.1187,  1.0942,  1.7791],
        [-0.7884, -0.2375,  2.8421]], device='cuda:0')
tensor([[ 1.0530,  0.1245,  0.1370],
        [ 1.0889,  1.7886,  1.1081],
        [-0.2099,  0.8741,  1.4774],
        [ 1.1187,  1.0942,  1.7791],
        [-0.7884, -0.2375,  2.8421]], dtype=torch.float64)
